import { ModelConfig } from "./types";

export const GOOGLE_MODELS: ModelConfig[] = [
  {
    id: "google/gemini-2.0-flash",
    creator: "google",
    infrastructureProvider: "vercel",
    model: "google/gemini-2.0-flash",
    displayName: "Gemini 2.0 Flash",
    description:
      "Gemini 2.0 Flash delivers next-gen features and improved capabilities, including superior speed, built-in tool use, multimodal generation, and a 1M token context window.",
    longDescription:
      "Gemini 2.0 Flash delivers next-gen features and improved capabilities, including superior speed, built-in tool use, multimodal generation, and a 1M token context window.",
    features: ["vision", "multimodal", "tool-calling"],
    specs: {
      contextLimit: 1048576,
      outputLimit: 8192,
      inputCost: 0.15,
      outputCost: 0.6,
      knowledgeCutoff: "2024-06",
      releaseDate: "2024-12-11",
    },
    allowedAttachmentTypes: ["image", "document", "audio", "video"],
    allowedMIMETypes: [
      "image/jpeg",
      "image/png",
      "image/gif",
      "image/webp",
      "application/pdf",
      "audio/mpeg",
      "audio/wav",
      "audio/ogg",
      "video/mp4",
    ],
    experimental: false,
    new: false,
    streaming: "word",
    pricingTier: "free",
    infrastructureProviderOptions: {
      provider: "vercel",
    },
  },
  {
    id: "google/gemini-2.0-flash-lite",
    creator: "google",
    infrastructureProvider: "vercel",
    model: "google/gemini-2.0-flash-lite",
    displayName: "Gemini 2.0 Flash Lite",
    description:
      "Gemini 2.0 Flash delivers next-gen features and improved capabilities, including superior speed, built-in tool use, multimodal generation, and a 1M token context window.",
    longDescription:
      "Gemini 2.0 Flash delivers next-gen features and improved capabilities, including superior speed, built-in tool use, multimodal generation, and a 1M token context window.",
    features: ["vision", "multimodal", "tool-calling"],
    specs: {
      contextLimit: 1048576,
      outputLimit: 8192,
      inputCost: 0.075,
      outputCost: 0.3,
      knowledgeCutoff: "2024-06",
      releaseDate: "2024-12-11",
    },
    allowedAttachmentTypes: ["image", "document", "audio", "video"],
    allowedMIMETypes: [
      "image/jpeg",
      "image/png",
      "image/gif",
      "image/webp",
      "application/pdf",
      "audio/mpeg",
      "audio/wav",
      "audio/ogg",
      "video/mp4",
    ],
    experimental: false,
    new: false,
    streaming: "word",
    pricingTier: "free",
    infrastructureProviderOptions: {
      provider: "vercel",
    },
  },
  {
    id: "google/gemini-2.5-flash",
    creator: "google",
    infrastructureProvider: "vercel",
    model: "google/gemini-2.5-flash",
    displayName: "Gemini 2.5 Flash",
    description:
      "Gemini 2.5 Flash is a thinking model that offers great, well-rounded capabilities. It is designed to offer a balance between price and performance with multimodal support and a 1M token context window.",
    longDescription:
      "Gemini 2.5 Flash is a thinking model that offers great, well-rounded capabilities. It is designed to offer a balance between price and performance with multimodal support and a 1M token context window.",
    features: ["vision", "reasoning", "multimodal", "tool-calling"],
    specs: {
      contextLimit: 1048576,
      outputLimit: 65536,
      inputCost: 0.3,
      outputCost: 2.5,
      cacheInputCost: 0.075,
      knowledgeCutoff: "2025-01",
      releaseDate: "2025-03-20",
    },
    allowedAttachmentTypes: ["image", "document", "audio", "video"],
    allowedMIMETypes: [
      "image/jpeg",
      "image/png",
      "image/gif",
      "image/webp",
      "application/pdf",
      "audio/mpeg",
      "audio/wav",
      "audio/ogg",
      "video/mp4",
    ],
    experimental: false,
    new: false,
    streaming: "word",
    pricingTier: "standard",
    infrastructureProviderOptions: {
      provider: "vercel",
    },
  },
  {
    id: "google/gemini-2.5-flash-lite",
    creator: "google",
    infrastructureProvider: "vercel",
    model: "google/gemini-2.5-flash-lite",
    displayName: "Gemini 2.5 Flash Lite",
    description:
      "Gemini 2.5 Flash-Lite is a balanced, low-latency model with configurable thinking budgets and tool connectivity (e.g., Google Search grounding and code execution). It supports multimodal input and offers a 1M-token context window.",
    longDescription:
      "Gemini 2.5 Flash-Lite is a balanced, low-latency model with configurable thinking budgets and tool connectivity (e.g., Google Search grounding and code execution). It supports multimodal input and offers a 1M-token context window.",
    features: ["vision", "reasoning", "multimodal", "tool-calling"],
    specs: {
      contextLimit: 128000,
      outputLimit: 4096,
      inputCost: 0.1,
      outputCost: 0.4,
      cacheInputCost: 0.025,
      knowledgeCutoff: "2024-01-01",
      releaseDate: "2024-01-01",
    },
    allowedAttachmentTypes: ["image", "document", "audio", "video"],
    allowedMIMETypes: [
      "image/jpeg",
      "image/png",
      "image/gif",
      "image/webp",
      "application/pdf",
      "audio/mpeg",
      "audio/wav",
      "audio/ogg",
      "video/mp4",
    ],
    experimental: false,
    new: false,
    streaming: "word",
    pricingTier: "free",
    infrastructureProviderOptions: {
      provider: "vercel",
    },
  },
  {
    id: "google/gemini-2.5-pro",
    creator: "google",
    infrastructureProvider: "vercel",
    model: "google/gemini-2.5-pro",
    displayName: "Gemini 2.5 Pro",
    description:
      "Gemini 2.5 Pro is our most advanced reasoning Gemini model, capable of solving complex problems. It features a 2M token context window and supports multimodal inputs including text, images, audio, video, and PDF documents.",
    longDescription:
      "Gemini 2.5 Pro is our most advanced reasoning Gemini model, capable of solving complex problems. It features a 2M token context window and supports multimodal inputs including text, images, audio, video, and PDF documents.",
    features: ["vision", "reasoning", "multimodal", "tool-calling"],
    specs: {
      contextLimit: 1048576,
      outputLimit: 65536,
      inputCost: 2.5,
      outputCost: 10,
      cacheInputCost: 0.625,
      knowledgeCutoff: "2025-01",
      releaseDate: "2025-03-20",
    },
    allowedAttachmentTypes: ["image", "document", "audio", "video"],
    allowedMIMETypes: [
      "image/jpeg",
      "image/png",
      "image/gif",
      "image/webp",
      "application/pdf",
      "audio/mpeg",
      "audio/wav",
      "audio/ogg",
      "video/mp4",
    ],
    experimental: false,
    new: false,
    streaming: "word",
    pricingTier: "premium",
    infrastructureProviderOptions: {
      provider: "vercel",
    },
  },
] as const;
